tinyMCE.init({
  mode: "textareas",
  editor_selector: "tinymce-simple",
  entity_encoding: "raw",
  extended_valid_elements: "object[width|height|classid|codebase],param[name|value],embed[src|type|width|height|flashvars|wmode],img[usemap|class|src|alt=|title|hspace|vspace|width|height|align|onmouseover|onmouseout|name|style],map[id|name],area[shape|alt|coords|href|target],iframe[src|width|height|name|align|frameborder|border],script[charset|defer|language|src|type]",
  relative_urls: false,
  media_strict: false, 
  verify_html: true,
  theme: "advanced",
  skin: "lemoon",
  theme_advanced_toolbar_location: "top",
  theme_advanced_toolbar_align: "left",
  theme_advanced_statusbar_location: "bottom",
  theme_advanced_resizing: true,
  theme_advanced_resize_horizontal: false,
  theme_advanced_buttons1: "bold,italic,underline,strikethrough,|,undo,redo,|,bullist,numlist",
  theme_advanced_buttons2: "",
  theme_advanced_buttons3: "",
  plugins: "paste"
});